### ISSUE TITLE
min/max function support

### ISSUE THREAD

**Issue by WieFel** [appsup-dart/expressions#24]
Hi,

I have expressions that look like `min(MAIN_rPowerBattery, 0) * (-1)`, with a context of `{MAIN_rPowerBattery: 0.86}`, but I always get the following error:
```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ type 'Null' is not a subtype of type 'Function'
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   ExpressionEvaluator.evalCallExpression (package:expressions/src/evaluator.dart:120:27)
flutter: │ #1   ExpressionEvaluator.eval (package:expressions/src/evaluator.dart:66:14)
flutter: │ #2   ExpressionEvaluator.evalBinaryExpression (package:expressions/src/evaluator.dart:143:16)
flutter: │ #3   ExpressionEvaluator.eval (package:expressions/src/evaluator.dart:72:14)
flutter: │ #4   _calculate (package:app/ui/charts/chart_math.dart:91:31)
flutter: │ #5   calculateResult.<anonymous closure> (package:app/ui/charts/chart_math.dart:53:28)
flutter: │ #6   ListExtensions.mapIndexed (package:collection/src/list_extensions.dart:144:20)
flutter: │ #7   _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:710:21)
```

It seems that it somehow expects a function mapping for `min`, or something similar. I suppose that `expressions` doesn't support the min/max function?

Is there a way to make min/max functions inside expressions work?

**Comment by WieFel** [comment]
Could resolve it myself by looking at issue #18.

I added the `dart:math`
```
...
var e = "some expression";
var context = {"myVariable": 5};

// define min and max function
context.addAll({"min": min, "max": max});

var result = _expressionEvaluator.eval(e, context);
```
